# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
import torch


X = torch.randn(7, 7)
X, X.shape

(tensor([[-1.4119,  1.6439,  1.1329,  1.4250, -0.3950,  0.7509, -2.4636],
         [-0.4706, -0.7843,  0.2414,  0.2332, -0.0524, -1.1448, -1.4375],
         [ 0.4853,  1.2378, -1.4467,  1.1125,  0.0422,  0.7224, -0.3980],
         [ 0.1387, -2.1314, -1.1731,  1.0601,  1.5891,  1.9239, -0.8555],
         [ 1.2543,  0.8517, -1.7261, -1.2351,  1.1061,  0.2745,  0.3074],
         [-0.4030,  0.1628,  0.6894,  1.5181, -0.5732,  0.3403,  0.6780],
         [ 2.1520,  1.0098,  0.5825,  0.7641,  1.8291,  0.5588,  0.6420]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
TENSOR = torch.randn(1, 7)
# Perform matrix multiplication
TENSOR = torch.matmul(X, TENSOR.T)
TENSOR, TENSOR.shape

(tensor([[-0.5169],
         [-2.3943],
         [ 3.6666],
         [-2.0541],
         [-1.4787],
         [ 4.5370],
         [ 0.2791]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

# Create two random tensors

TENSOR1 = torch.randn(1, 7)
TENSOR2 = torch.randn(1, 7)

# Matrix multiply tensors

result = torch.matmul(TENSOR1, TENSOR2.T)
result, result.shape

(tensor([[-4.8165]]), torch.Size([1, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2, 3)).to(device)
tensor_B = torch.rand(size=(2, 3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B

tensor_AB = tensor_A @ tensor_B.T
tensor_AB

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
max = tensor_AB.max()
# Find min
min = tensor_AB.min()
print(f"Max: {max}, Min: {min}")
# Find argmax

Max: 0.5617256760597229, Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max
arg_max = torch.argmax(tensor_AB)

# Find arg min
arg_min = torch.argmin(tensor_AB)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [9]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.randn(1, 1, 1, 10)

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors and their shapes
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]]) torch.Size([1, 1, 1, 10])
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822]) torch.Size([10])
